"""Static knowledge base for the Behavioral Intelligence Engine.

This mirrors the data that powers the live v1 app, expressed as plain Python
data structures so the engine functions stay pure and testable.
"""
from __future__ import annotations

# --- The 10 behavioural dimensions -----------------------------------------
PARAMS: dict[str, dict] = {
    "awareness":    {"label": "Awareness",    "color": "#3b82f6"},
    "action":       {"label": "Action",       "color": "#ef4444"},
    "discipline":   {"label": "Discipline",   "color": "#f59e0b"},
    "resilience":   {"label": "Resilience",   "color": "#22c55e"},
    "adaptability": {"label": "Adaptability", "color": "#06b6d4"},
    "selftrust":    {"label": "Self-trust",   "color": "#a855f7"},
    "boundaries":   {"label": "Boundaries",   "color": "#ec4899"},
    "patience":     {"label": "Patience",     "color": "#6366f1"},
    "clarity":      {"label": "Clarity",      "color": "#14b8a6"},
    "growth":       {"label": "Growth",       "color": "#84cc16"},
}
PARAM_KEYS: list[str] = list(PARAMS.keys())

# --- A compact, functional question bank (3 per dimension) ------------------
# Each multiple-choice option carries a score; the engine normalises per dim.
QUESTION_BANK: dict[str, list[dict]] = {
    "awareness": [
        {"id": "awareness_1", "text": "When something repeats in your life, how likely are you to spot the pattern?",
         "options": [{"label": "I usually name it quickly", "score": 8},
                     {"label": "I notice eventually", "score": 5},
                     {"label": "I tend to think each time is unrelated", "score": 2}]},
        {"id": "awareness_2", "text": "Someone names a blind spot of yours. Your first reaction?",
         "options": [{"label": "Curiosity — there's probably something to it", "score": 8},
                     {"label": "Sting first, then I consider it", "score": 5},
                     {"label": "I mostly dismiss it", "score": 2}]},
        {"id": "awareness_3", "text": "How well could you predict your own biggest habit?",
         "options": [{"label": "Very accurately", "score": 8},
                     {"label": "Roughly", "score": 5},
                     {"label": "I'd be way off", "score": 2}]},
    ],
    "action": [
        {"id": "action_1", "text": "An idea excites you tonight. By tomorrow evening?",
         "options": [{"label": "I've taken one concrete step", "score": 8},
                     {"label": "I've researched but not acted", "score": 4},
                     {"label": "The excitement faded", "score": 1}]},
        {"id": "action_2", "text": "A conversation you've needed to have for weeks — when does it happen?",
         "options": [{"label": "This week", "score": 7},
                     {"label": "Eventually, when forced", "score": 3},
                     {"label": "It keeps not happening", "score": 1}]},
        {"id": "action_3", "text": "When you know the right next step, how fast do you take it?",
         "options": [{"label": "Almost immediately", "score": 8},
                     {"label": "After a while", "score": 4},
                     {"label": "I sit on it", "score": 1}]},
    ],
    "discipline": [
        {"id": "discipline_1", "text": "On a completely unmotivated day, your top habit…",
         "options": [{"label": "Runs anyway, on autopilot", "score": 8},
                     {"label": "Slows but survives", "score": 5},
                     {"label": "Stops until I feel better", "score": 2}]},
        {"id": "discipline_2", "text": "A habit you started two weeks ago is now…",
         "options": [{"label": "Still going on a system", "score": 8},
                     {"label": "On and off", "score": 4},
                     {"label": "Quietly abandoned", "score": 1}]},
        {"id": "discipline_3", "text": "How much of your week runs on set routines?",
         "options": [{"label": "Most of it", "score": 8},
                     {"label": "Some", "score": 5},
                     {"label": "Almost none", "score": 2}]},
    ],
    "resilience": [
        {"id": "resilience_1", "text": "After a bad week, how fast are you steady again?",
         "options": [{"label": "A day or two", "score": 7},
                     {"label": "Most of the week", "score": 3},
                     {"label": "It spills into the next week", "score": 1}]},
        {"id": "resilience_2", "text": "When stress piles up, your sleep/food/movement…",
         "options": [{"label": "Mostly hold", "score": 7},
                     {"label": "Slip a bit", "score": 4},
                     {"label": "Collapse first", "score": 1}]},
        {"id": "resilience_3", "text": "Something unfair happens. A week later?",
         "options": [{"label": "Processed and moved on", "score": 7},
                     {"label": "Still simmering but functioning", "score": 4},
                     {"label": "It's still running the show", "score": 1}]},
    ],
    "adaptability": [
        {"id": "adaptability_1", "text": "A plan clearly stops working. Your instinct?",
         "options": [{"label": "Adjust the approach quickly", "score": 7},
                     {"label": "Push harder on the old way", "score": 2},
                     {"label": "Freeze and avoid deciding", "score": 1}]},
        {"id": "adaptability_2", "text": "New evidence shows your favourite method is now wrong. You…",
         "options": [{"label": "Switch tools, a little reluctantly", "score": 7},
                     {"label": "Tweak and hope", "score": 3},
                     {"label": "Keep going — it worked before", "score": 1}]},
        {"id": "adaptability_3", "text": "How willing are you to drop a long-held belief given new evidence?",
         "options": [{"label": "Very willing", "score": 7},
                     {"label": "Somewhat", "score": 4},
                     {"label": "Very reluctant", "score": 1}]},
    ],
    "selftrust": [
        {"id": "selftrust_1", "text": "After a hard solo decision, a week later you usually feel…",
         "options": [{"label": "It was the right call", "score": 7},
                     {"label": "Mixed", "score": 4},
                     {"label": "I wish I'd trusted my gut", "score": 1}]},
        {"id": "selftrust_2", "text": "Before believing a decision is right, how much do you need others to agree?",
         "options": [{"label": "Barely at all", "score": 7},
                     {"label": "Somewhat", "score": 4},
                     {"label": "Quite a lot", "score": 1}]},
        {"id": "selftrust_3", "text": "Someone confidently disagrees with a call you made. You…",
         "options": [{"label": "Hold if I still believe it", "score": 7},
                     {"label": "Start doubting myself", "score": 2},
                     {"label": "Depends who it is", "score": 4}]},
    ],
    "boundaries": [
        {"id": "boundaries_1", "text": "Over the last month, how often did you agree to things you didn't want to?",
         "options": [{"label": "Rarely", "score": 7},
                     {"label": "A few times", "score": 4},
                     {"label": "Often", "score": 1}]},
        {"id": "boundaries_2", "text": "A 'quick favour' will eat your evening. You…",
         "options": [{"label": "Say no or set a limit", "score": 7},
                     {"label": "Do it and resent it", "score": 2},
                     {"label": "Do it and call it fine", "score": 3}]},
        {"id": "boundaries_3", "text": "Someone keeps overstepping the same line. By now you've…",
         "options": [{"label": "Named it clearly", "score": 7},
                     {"label": "Hinted and hoped", "score": 3},
                     {"label": "Gone quiet and withdrawn", "score": 2}]},
    ],
    "patience": [
        {"id": "patience_1", "text": "Three months in with no visible payoff (timeline was realistic). Staying the course is…",
         "options": [{"label": "Not hard", "score": 7},
                     {"label": "Manageable", "score": 5},
                     {"label": "Very hard — I tend to bail", "score": 2}]},
        {"id": "patience_2", "text": "Waiting on a result you can't control, you mostly…",
         "options": [{"label": "Get on with other things", "score": 7},
                     {"label": "Distract but stay tense", "score": 4},
                     {"label": "Check obsessively", "score": 2}]},
        {"id": "patience_3", "text": "Effort now, no feedback for a long time. How comfortable are you?",
         "options": [{"label": "Very comfortable", "score": 7},
                     {"label": "Somewhat", "score": 4},
                     {"label": "Very uncomfortable", "score": 1}]},
    ],
    "clarity": [
        {"id": "clarity_1", "text": "Asked what you want two years out, how does it go?",
         "options": [{"label": "I answer immediately and specifically", "score": 7},
                     {"label": "After a minute's thought", "score": 4},
                     {"label": "I don't have a clear answer", "score": 1}]},
        {"id": "clarity_2", "text": "How well does your daily time match what you say matters most?",
         "options": [{"label": "Closely", "score": 7},
                     {"label": "Somewhat", "score": 4},
                     {"label": "Barely", "score": 1}]},
        {"id": "clarity_3", "text": "Do you know what 'enough' looks like for you?",
         "options": [{"label": "Yes, I could describe it", "score": 7},
                     {"label": "Vaguely", "score": 4},
                     {"label": "No — it keeps moving", "score": 1}]},
    ],
    "growth": [
        {"id": "growth_1", "text": "You read about someone failing the way you might. You…",
         "options": [{"label": "Extract the lesson before I risk it", "score": 8},
                     {"label": "Note it, rarely apply it", "score": 3},
                     {"label": "Assume I'm different", "score": 1}]},
        {"id": "growth_2", "text": "After a setback, how fast from 'why me' to 'what's the lesson'?",
         "options": [{"label": "Quickly", "score": 7},
                     {"label": "Eventually", "score": 4},
                     {"label": "Slowly, if ever", "score": 1}]},
        {"id": "growth_3", "text": "Your most recent setback — right now it's mostly…",
         "options": [{"label": "A lesson I can name", "score": 7},
                     {"label": "Still a sore spot", "score": 2},
                     {"label": "Unexamined", "score": 3}]},
    ],
}

IMPROVEMENT_PHRASES: dict[str, str] = {
    "awareness": "Your own patterns can stay invisible until someone names them for you.",
    "action": "Insight doesn't always make it to an actual first move.",
    "discipline": "Follow-through is closely tied to how motivated you feel that day.",
    "resilience": "Stress and discomfort pull you off track more than you'd like.",
    "adaptability": "You can stay with a familiar approach past the point it serves you.",
    "selftrust": "You look for outside agreement before trusting your own call.",
    "boundaries": "Other people's urgency has a way of becoming your own.",
    "patience": "Slow, invisible progress is genuinely hard to sit with.",
    "clarity": "What you want can shift with who you're around or what you just read.",
    "growth": "Lessons tend to arrive through direct pain rather than observation.",
}

# --- Recommendations (each carries a "why") --------------------------------
RECOMMENDATIONS: dict[str, dict] = {
    "awareness": {"book": ("The Untethered Soul — Michael A. Singer", "observing your reactions instead of being run by them"),
                  "podcast": ("The Happiness Lab — Dr. Laurie Santos", "noticing your own mind"),
                  "habit": "Each night, log the moment you reacted strongest and what came right before it."},
    "action": {"book": ("The War of Art — Steven Pressfield", "beating the resistance before you start"),
               "podcast": ("The Tim Ferriss Show", "starting before you feel ready"),
               "habit": "Use a 2-minute rule: at the first sign of avoidance, do just two minutes."},
    "discipline": {"book": ("Atomic Habits — James Clear", "systems that don't depend on motivation"),
                   "podcast": ("The Diary of a CEO", "the systems behind consistent people"),
                   "habit": "Pre-decide tomorrow's single key task tonight, in writing."},
    "resilience": {"book": ("Man's Search for Meaning — Viktor Frankl", "meaning under real adversity"),
                   "podcast": ("Feel Better, Live More — Dr. Rangan Chatterjee", "practical resilience"),
                   "habit": "Define one reset ritual you run within 24 hours of any setback."},
    "adaptability": {"book": ("Who Moved My Cheese? — Spencer Johnson", "reacting to change quickly"),
                     "podcast": ("WorkLife with Adam Grant", "rethinking how you operate"),
                     "habit": "Weekly, ask: what am I doing out of habit that no longer fits?"},
    "selftrust": {"book": ("The Gifts of Imperfection — Brené Brown", "trusting your own judgment"),
                  "podcast": ("The Mel Robbins Podcast", "building decision confidence"),
                  "habit": "Make one small call this week without asking anyone first."},
    "boundaries": {"book": ("Boundaries — Cloud & Townsend", "where your responsibility ends"),
                   "podcast": ("Where Should We Begin? — Esther Perel", "the dynamics of saying no"),
                   "habit": "Practice one low-stakes 'no' before the week ends."},
    "patience": {"book": ("The Obstacle Is the Way — Ryan Holiday", "holding steady without a quick payoff"),
                 "podcast": ("The Knowledge Project — Shane Parrish", "long-term thinking"),
                 "habit": "Track a leading indicator (effort, not outcome)."},
    "clarity": {"book": ("Essentialism — Greg McKeown", "deciding what actually matters"),
                "podcast": ("The Tim Ferriss Show", "choosing what to optimise for"),
                "habit": "Write one sentence on what you're optimising for this year; reread weekly."},
    "growth": {"book": ("Mindset — Carol S. Dweck", "treating effort and setbacks as the mechanism of growth"),
               "podcast": ("Hidden Brain — Shankar Vedantam", "the psychology of change"),
               "habit": "Before a big move, learn from one person who failed at it first."},
}

# --- Symbolic avatars -------------------------------------------------------
AVATARS: dict[str, dict] = {
    "explorer":   {"name": "The Explorer",   "emoji": "🧭", "dims": ["awareness", "growth", "adaptability"]},
    "architect":  {"name": "The Architect",  "emoji": "📐", "dims": ["discipline", "clarity", "patience"]},
    "strategist": {"name": "The Strategist", "emoji": "♟️", "dims": ["clarity", "selftrust", "patience"]},
    "builder":    {"name": "The Builder",    "emoji": "🔨", "dims": ["action", "discipline", "adaptability"]},
    "visionary":  {"name": "The Visionary",  "emoji": "🌠", "dims": ["growth", "clarity", "adaptability"]},
    "guardian":   {"name": "The Guardian",   "emoji": "🛡️", "dims": ["boundaries", "resilience", "selftrust"]},
    "catalyst":   {"name": "The Catalyst",   "emoji": "⚡", "dims": ["action", "adaptability", "awareness"]},
}

# --- Life domains & professional competencies -------------------------------
DOMAINS: list[dict] = [
    {"name": "Career",         "dims": ["discipline", "clarity", "action", "growth"]},
    {"name": "Relationships",  "dims": ["boundaries", "awareness", "selftrust", "resilience"]},
    {"name": "Health & Stress","dims": ["resilience", "patience", "boundaries"]},
    {"name": "Money",          "dims": ["discipline", "patience", "clarity"]},
    {"name": "Learning",       "dims": ["growth", "awareness", "adaptability"]},
    {"name": "Leadership",     "dims": ["selftrust", "clarity", "action", "boundaries"]},
]

COMPETENCIES: list[dict] = [
    {"name": "Problem Solving",        "dims": ["clarity", "adaptability", "growth"]},
    {"name": "Communication",          "dims": ["boundaries", "awareness", "selftrust"]},
    {"name": "Leadership",             "dims": ["selftrust", "clarity", "action"]},
    {"name": "Learning Speed",         "dims": ["growth", "adaptability", "awareness"]},
    {"name": "Analytical Thinking",    "dims": ["clarity", "awareness"]},
    {"name": "Execution & Reliability","dims": ["discipline", "action", "patience"]},
    {"name": "Resilience",             "dims": ["resilience", "patience"]},
    {"name": "Collaboration",          "dims": ["boundaries", "awareness"]},
]
